# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('national_id', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="National id must be entered in the format: '33335501'. Up to 8 digits allowed ", regex='^\\+?1?\\d{8,8}$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '07123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('TN', 'tenant'), ('MN', 'manager'), ('AD', 'admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('deposit_amount', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('rent_amount', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('day_to_pay_rent', models.IntegerField()),
                ('rent_payment_type', models.CharField(choices=[('DY', 'Days'), ('MN', 'Months'), ('WK', 'Weeks'), ('YR', 'Years')], max_length=10)),
                ('rent_start_date', models.DateField()),
            ],
            options={
                'verbose_name': 'agreement',
                'verbose_name_plural': 'agreements',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('tittle', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('response', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'message',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message="National id must be entered in the format: '33335501'. Up to 8 digits allowed ", regex='^\\+?1?\\d{8,8}$')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '07123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')])),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('year_of_completion', models.DateField()),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=100)),
                ('amount_due', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('amount_paid', models.CharField(blank=True, default=0, max_length=20, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('transaction_type', models.CharField(blank=True, choices=[('RN', 'rent'), ('SC', 'service charge'), ('DP', 'deposit'), ('MT', 'maintenance')], max_length=20)),
                ('transaction_status', models.CharField(choices=[('P', 'paid'), ('UN', 'unpaid')], max_length=20)),
                ('date_paid', models.CharField(blank=True, max_length=100)),
                ('date_due', models.DateField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tenant')),
                ('property', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=30)),
                ('no_of_bed', models.IntegerField()),
                ('no_of_bathroom', models.IntegerField()),
                ('status', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Unit'),
        ),
        migrations.AddField(
            model_name='owner',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AddField(
            model_name='message',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AddField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Tenant'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tenant'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Unit'),
        ),
    ]
