# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '07123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
